import { isMeetingLanguage } from '@/modules/meetings/domain/meeting.types';
import { RecordingProgress } from '@/modules/recording/presentation/RecordingProgress';
import TaskEditor from '@/modules/tasks/presentation/components/TaskEditor';
import { formatDate } from '@/shared/lib/formatDate';
import { Alert, Button, Checkbox, Loader, Modal, Select, Textarea, TextInput } from '@mantine/core';
import { ArrowLeft, Check, ChevronRight, Download, FileAudio, FileText, Pencil, Plus, Printer, Search, Users, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { tabs, useMeetingModel } from '../models/useMeetingModel';
import styles from './MeetingPage.module.css';
const languageOptions = [{ value: 'ru', label: 'Русский' }, { value: 'kk', label: 'Қазақша' }, { value: 'mixed', label: 'Смешанный' }];
const statusLabel = { todo: 'К выполнению', 'in-progress': 'В работе', done: 'Выполнено' };


function Initials({ name }: { name: string }) {
  const initials = name.split(/\s+/).slice(0, 2).map((word) => word[0]).join('').toUpperCase();
  return <span className={styles.initials} aria-hidden="true">{initials || '—'}</span>;
}

export default function MeetingPage() {
  const { meeting, meetingTasks, loading, error, tab, metadataOpen, setMetadataOpen, participantsOpen, setParticipantsOpen, exportOpen, setExportOpen, includeTranscript, setIncludeTranscript, taskOpen, setTaskOpen, editingTask, setEditingTask, editingSegment, setEditingSegment, transcriptQuery, setTranscriptQuery, summaryDraft, setSummaryDraft, summaryEditing, setSummaryEditing, metadata, setMetadata, peopleDraft, setPeopleDraft, segmentDraft, setSegmentDraft, busy, localError, setLocalError, sourceUrl, selectTab, saveMeeting, startSegment, saveSegment, saveParticipants, downloadDocx, printProtocol } = useMeetingModel();

  if (loading) return <div className={styles.loading}><Loader size="sm" /><span>Открываем встречу…</span></div>;
  if (!meeting) return <div className={styles.missing}><FileText size={27} /><h1>Встреча не найдена</h1><p>Запись могла быть удалена или ссылка устарела.</p><Button component={Link} to="/meetings" variant="light">К списку встреч</Button></div>;

  const filteredSegments = meeting.transcript.filter((segment) => `${segment.speaker} ${segment.role} ${segment.section || ''} ${segment.text}`.toLowerCase().includes(transcriptQuery.trim().toLowerCase()));
  const sections = [...new Set(meeting.transcript.map((segment) => segment.section).filter(Boolean))];
  const pending = meeting.status === 'pending';
  const sourceKind = meeting.source?.type.startsWith('video/') ? 'Видео' : meeting.source?.type.startsWith('audio/') ? 'Аудио' : 'Файл';

  return <div className={styles.page}>
    <div className={styles.backline}><Link to="/meetings"><ArrowLeft size={15} /> Все встречи</Link><span><ChevronRight size={13} /> {meeting.number ? `Встреча ${String(meeting.number).padStart(2, '0')}` : 'Встреча'}</span></div>
    <header className={styles.header}>
      <div className={styles.heading}><div className={styles.eyebrow}>{meeting.kind === 'example' ? 'ПРИМЕР · ' : 'ЛОКАЛЬНАЯ ЗАПИСЬ · '} {meeting.number ? `№ ${String(meeting.number).padStart(2, '0')}` : 'РАБОЧИЙ ДОКУМЕНТ'}</div><h1>{meeting.title}</h1><div className={styles.metadata}><span>{meeting.organization || 'Организация не указана'}</span><span className={styles.metaDot}>·</span><span>{formatDate(meeting.date)}</span><button type="button" onClick={() => setMetadataOpen(true)} aria-label="Изменить реквизиты встречи"><Pencil size={13} /> Изменить</button></div></div>
      <div className={styles.headerActions}><Button variant="default" leftSection={<Download size={16} />} onClick={() => setExportOpen(true)}>Экспорт</Button><Button onClick={() => { setEditingTask(undefined); setTaskOpen(true); }} leftSection={<Plus size={16} />}>Поручение</Button></div>
    </header>

    {meeting.backendRunId && <RecordingProgress runId={meeting.backendRunId} className={styles.alert} />}
    {(error || localError) && <Alert color="red" className={styles.alert} withCloseButton onClose={() => setLocalError('')}>{localError || error}</Alert>}
    {pending && !meeting.backendRunId && <div className={styles.pending}><FileAudio size={17} /><div><strong>Запись сохранена в этом браузере.</strong><span>Расшифровка появится после подключения обработки. Сводку и поручения можно заполнить вручную.</span></div></div>}

    <div className={styles.workspace}>
      <aside className={styles.outline} aria-label="Разделы встречи"><div className={styles.railTitle}>ДОКУМЕНТ</div><nav>{tabs.map((item, index) => <button type="button" key={item.id} className={`${styles.outlineItem} ${tab === item.id ? styles.active : ''}`} onClick={() => selectTab(item.id)}><span className={styles.outlineNumber}>{String(index + 1).padStart(2, '0')}</span><span><strong>{item.label}</strong><small>{item.detail}</small></span></button>)}</nav><div className={styles.outlineFoot}>{meeting.transcript.length} реплик · {meetingTasks.length} поручений</div></aside>
      <div className={styles.mobileTabs} role="tablist" aria-label="Разделы встречи">{tabs.map((item) => <button type="button" role="tab" aria-label={item.label} aria-selected={tab === item.id} key={item.id} className={tab === item.id ? styles.mobileActive : ''} onClick={() => selectTab(item.id)}>{item.id === 'transcript' ? 'Текст' : item.id === 'tasks' ? 'Задачи' : item.label}</button>)}</div>

      <article className={styles.paper}>
        {tab === 'summary' && <>
          <div className={styles.documentTop}><span>01 / СВОДКА ВСТРЕЧИ</span><span>{meeting.kind === 'example' ? 'Пример документа' : 'Локальный документ'}</span></div>
          <div className={styles.paperHeader}><p className={styles.kicker}>ВСТРЕЧА {meeting.number ? `№ ${meeting.number}` : ''}</p><h2>{meeting.title}</h2><p>{meeting.organization || 'Организация не указана'} <span>·</span> {formatDate(meeting.date)}</p></div>
          <section className={styles.section}><div className={styles.sectionHeading}><div><span>01</span><h3>Краткое содержание</h3></div>{!summaryEditing && <button type="button" onClick={() => { setSummaryDraft(meeting.summary); setSummaryEditing(true); }}><Pencil size={14} /> Редактировать</button>}</div>
            {summaryEditing ? <div className={styles.editBlock}><Textarea autosize minRows={8} value={summaryDraft} onChange={(event) => setSummaryDraft(event.currentTarget.value)} placeholder="Запишите основные вопросы и решения встречи" aria-label="Краткое содержание" /><div className={styles.editActions}><Button variant="default" onClick={() => setSummaryEditing(false)}>Отмена</Button><Button loading={busy} onClick={() => saveMeeting({ summary: summaryDraft.trim() }, () => setSummaryEditing(false))}>Сохранить</Button></div></div> : meeting.summary.trim() ? <div className={styles.prose}>{meeting.summary.split(/\n\s*\n/).map((part, index) => <p key={index}>{part}</p>)}</div> : <div className={styles.emptyInline}>Сводка пока не заполнена. Добавьте основные вопросы и решения вручную.</div>}
          </section>
          <section className={styles.section}><div className={styles.sectionHeading}><div><span>02</span><h3>Участники</h3></div><button type="button" onClick={() => setParticipantsOpen(true)}><Pencil size={14} /> Изменить</button></div>{meeting.participants.length ? <div className={styles.people}>{meeting.participants.map((person) => <div className={styles.person} key={person.id}><Initials name={person.name} /><div><strong>{person.name}</strong><small>{person.role || 'Роль не указана'}</small></div></div>)}</div> : <div className={styles.emptyInline}>Участники не указаны.</div>}</section>
          {sections.length > 0 && <section className={styles.section}><div className={styles.sectionHeading}><div><span>03</span><h3>Темы разговора</h3></div></div><ol className={styles.topicList}>{sections.map((section) => <li key={section}>{section}</li>)}</ol></section>}
        </>}

        {tab === 'transcript' && <>
          <div className={styles.documentTop}><span>02 / РАСШИФРОВКА</span><span>{meeting.transcript.length} реплик</span></div>
          <div className={styles.tabHeading}><div><p className={styles.kicker}>ИСТОЧНИК ВСТРЕЧИ</p><h2>Расшифровка</h2><p>Реплики доступны для ручной правки. Изменения сохраняются в этой встрече.</p></div><Button variant="default" size="sm" leftSection={<Plus size={15} />} onClick={() => startSegment()}>Добавить реплику</Button></div>
          {meeting.source && <div className={styles.source}><FileAudio size={19} /><div><strong>{meeting.source.name}</strong><span>{sourceKind} · {(meeting.source.size / 1024 / 1024).toFixed(1)} МБ</span></div></div>}
          {sourceUrl && meeting.source?.type.startsWith('audio/') && <audio className={styles.player} controls src={sourceUrl}>Ваш браузер не поддерживает воспроизведение аудио.</audio>}
          {sourceUrl && meeting.source?.type.startsWith('video/') && <video className={styles.video} controls src={sourceUrl}>Ваш браузер не поддерживает воспроизведение видео.</video>}
          <div className={styles.search}><Search size={16} /><input value={transcriptQuery} onChange={(event) => setTranscriptQuery(event.currentTarget.value)} placeholder="Поиск по репликам" aria-label="Поиск по расшифровке" />{transcriptQuery && <button type="button" onClick={() => setTranscriptQuery('')} aria-label="Очистить поиск"><X size={15} /></button>}</div>
          {filteredSegments.length ? <div className={styles.segments}>{filteredSegments.map((segment, index) => <div key={segment.id} className={styles.segment}>{segment.section && (index === 0 || filteredSegments[index - 1]?.section !== segment.section) && <h3 className={styles.segmentSection}>{segment.section}</h3>}<div className={styles.segmentRow}><Initials name={segment.speaker} /><div><div className={styles.segmentSpeaker}><strong>{segment.speaker}</strong><span>{segment.role}</span><button type="button" onClick={() => startSegment(segment)} aria-label={`Изменить реплику: ${segment.speaker}`}><Pencil size={14} /></button></div><p>{segment.text}</p></div></div></div>)}</div> : <div className={styles.emptyInline}>{transcriptQuery ? 'По этому запросу реплик нет.' : 'Расшифровки пока нет. Реплики можно добавить вручную.'}</div>}
        </>}

        {tab === 'protocol' && <>
          <div className={styles.documentTop}><span>03 / ПРОТОКОЛ</span><span>Доступен для экспорта</span></div>
          <div className={styles.protocolTitle}><p>{meeting.organization || 'Организация не указана'}</p><h2>ПРОТОКОЛ{meeting.number ? ` № ${meeting.number}` : ''}</h2><h3>{meeting.title}</h3><div><span>{formatDate(meeting.date)}</span><span>{languageOptions.find((option) => option.value === meeting.language)?.label}</span></div></div>
          <section className={styles.protocolSection}><h4>Участники</h4>{meeting.participants.length ? <p>{meeting.participants.map((person) => person.name).join(', ')}</p> : <p className={styles.placeholder}>Не указаны</p>}</section>
          <section className={styles.protocolSection}><div className={styles.protocolSectionHeading}><h4>Краткое содержание</h4><button type="button" onClick={() => { setSummaryDraft(meeting.summary); setSummaryEditing(true); selectTab('summary'); }}><Pencil size={13} /> Править</button></div>{meeting.summary ? <div className={styles.prose}>{meeting.summary.split(/\n\s*\n/).map((part, index) => <p key={index}>{part}</p>)}</div> : <p className={styles.placeholder}>Не заполнено</p>}</section>
          <section className={styles.protocolSection}><div className={styles.protocolSectionHeading}><h4>Поручения</h4><button type="button" onClick={() => selectTab('tasks')}>Открыть список <ChevronRight size={13} /></button></div>{meetingTasks.length ? <div className={styles.protocolTableWrap}><table className={styles.protocolTable}><thead><tr><th>№</th><th>Поручение</th><th>Ответственный</th><th>Срок</th></tr></thead><tbody>{meetingTasks.map((task, index) => <tr key={task.id}><td>{String(index + 1).padStart(2, '0')}</td><td>{task.title}</td><td>{task.assignee || 'Не назначен'}</td><td>{task.deadlineText || 'Не указан'}</td></tr>)}</tbody></table></div> : <p className={styles.placeholder}>Поручений пока нет.</p>}</section>
          <div className={styles.protocolFooter}>Составлено в рабочем пространстве · {meeting.kind === 'example' ? 'пример для ознакомления' : 'локальный документ'}</div>
        </>}

        {tab === 'tasks' && <>
          <div className={styles.documentTop}><span>04 / ПОРУЧЕНИЯ</span><span>{meetingTasks.length} записей</span></div>
          <div className={styles.tabHeading}><div><p className={styles.kicker}>ПО ИТОГАМ ВСТРЕЧИ</p><h2>Поручения</h2><p>Ответственные и сроки сохраняются вместе с этой встречей.</p></div><Button size="sm" leftSection={<Plus size={15} />} onClick={() => { setEditingTask(undefined); setTaskOpen(true); }}>Добавить</Button></div>
          {meetingTasks.length ? <div className={styles.taskList}>{meetingTasks.map((task, index) => <button type="button" key={task.id} className={styles.taskRow} onClick={() => { setEditingTask(task); setTaskOpen(true); }}><span className={styles.taskNumber}>{String(index + 1).padStart(2, '0')}</span><span className={styles.taskMain}><strong>{task.title}</strong><small>{task.assignee || 'Ответственный не указан'} · {task.deadlineText || 'Срок не указан'}</small></span><span className={`${styles.taskStatus} ${task.status === 'done' ? styles.statusDone : ''}`}>{task.status === 'done' && <Check size={13} />}{statusLabel[task.status]}</span><ChevronRight size={15} /></button>)}</div> : <div className={styles.emptyInline}>Поручений пока нет. Добавьте первое поручение вручную.</div>}
        </>}
      </article>

      <aside className={styles.context} aria-label="Контекст встречи"><div className={styles.contextHead}><span>КОНТЕКСТ</span><Users size={16} /></div><div className={styles.contextSection}><div className={styles.contextTitle}><strong>Участники</strong><button type="button" onClick={() => setParticipantsOpen(true)}>Изменить</button></div><div className={styles.contextPeople}>{meeting.participants.slice(0, 5).map((person) => <div key={person.id}><Initials name={person.name} /><span>{person.name}</span></div>)}{meeting.participants.length === 0 && <small>Не указаны</small>}</div></div><div className={styles.contextSection}><div className={styles.contextTitle}><strong>Поручения</strong><button type="button" onClick={() => selectTab('tasks')}>Все {meetingTasks.length}</button></div>{meetingTasks.slice(0, 3).map((task) => <button type="button" className={styles.contextTask} key={task.id} onClick={() => { setEditingTask(task); setTaskOpen(true); }}><span className={task.status === 'done' ? styles.taskDotDone : styles.taskDot} /><span><strong>{task.title}</strong><small>{task.assignee || 'Не назначен'} · {task.deadlineText || 'Без срока'}</small></span></button>)}{meetingTasks.length === 0 && <small>Пока нет поручений</small>}<button className={styles.contextAdd} type="button" onClick={() => { setEditingTask(undefined); setTaskOpen(true); }}><Plus size={14} /> Добавить поручение</button></div></aside>
    </div>

    <Modal opened={metadataOpen} onClose={() => setMetadataOpen(false)} title="Реквизиты встречи" centered><div className={styles.modalFields}>{localError && <Alert color="red">{localError}</Alert>}<TextInput label="Тема встречи" required value={metadata.title} onChange={(event) => setMetadata({ ...metadata, title: event.currentTarget.value })} /><TextInput label="Организация" value={metadata.organization} onChange={(event) => setMetadata({ ...metadata, organization: event.currentTarget.value })} /><TextInput label="Дата встречи" type="date" value={metadata.date} onChange={(event) => setMetadata({ ...metadata, date: event.currentTarget.value })} /><Select label="Язык" data={languageOptions} value={metadata.language} onChange={(value) => setMetadata({ ...metadata, language: isMeetingLanguage(value) ? value : metadata.language })} /><div className={styles.modalActions}><Button variant="default" onClick={() => setMetadataOpen(false)}>Отмена</Button><Button loading={busy} disabled={!metadata.title.trim()} onClick={() => saveMeeting({ title: metadata.title.trim(), organization: metadata.organization.trim(), date: metadata.date || null, language: metadata.language }, () => setMetadataOpen(false))}>Сохранить</Button></div></div></Modal>
    <Modal opened={participantsOpen} onClose={() => setParticipantsOpen(false)} title="Участники" centered><div className={styles.modalFields}>{localError && <Alert color="red">{localError}</Alert>}<Textarea label="По одному участнику на строке" description="Формат: Имя — роль" autosize minRows={6} value={peopleDraft} onChange={(event) => setPeopleDraft(event.currentTarget.value)} /><div className={styles.modalActions}><Button variant="default" onClick={() => setParticipantsOpen(false)}>Отмена</Button><Button loading={busy} onClick={saveParticipants}>Сохранить</Button></div></div></Modal>
    <Modal opened={editingSegment !== null} onClose={() => setEditingSegment(null)} title={editingSegment?.id ? 'Изменить реплику' : 'Добавить реплику'} centered><div className={styles.modalFields}>{localError && <Alert color="red">{localError}</Alert>}<TextInput label="Говорящий" required value={segmentDraft.speaker} onChange={(event) => setSegmentDraft({ ...segmentDraft, speaker: event.currentTarget.value })} /><TextInput label="Роль" value={segmentDraft.role} onChange={(event) => setSegmentDraft({ ...segmentDraft, role: event.currentTarget.value })} /><TextInput label="Раздел" value={segmentDraft.section} onChange={(event) => setSegmentDraft({ ...segmentDraft, section: event.currentTarget.value })} /><Textarea label="Текст реплики" required autosize minRows={5} value={segmentDraft.text} onChange={(event) => setSegmentDraft({ ...segmentDraft, text: event.currentTarget.value })} /><div className={styles.modalActions}><Button variant="default" onClick={() => setEditingSegment(null)}>Отмена</Button><Button loading={busy} onClick={saveSegment}>Сохранить</Button></div></div></Modal>
    <Modal opened={exportOpen} onClose={() => setExportOpen(false)} title="Экспорт протокола" centered><div className={styles.exportModal}>{localError && <Alert color="red" mb="sm">{localError}</Alert>}<p>В документ войдут реквизиты встречи, участники, сводка и поручения.</p><Checkbox label="Добавить полную расшифровку" checked={includeTranscript} onChange={(event) => setIncludeTranscript(event.currentTarget.checked)} /><div className={styles.exportActions}><Button variant="default" leftSection={<Printer size={16} />} onClick={printProtocol}>Печать / PDF</Button><Button loading={busy} leftSection={<Download size={16} />} onClick={downloadDocx}>Скачать DOCX</Button></div><small>PDF сохраняется через диалог печати браузера.</small></div></Modal>
    <TaskEditor opened={taskOpen} onClose={() => setTaskOpen(false)} task={editingTask} meetingId={meeting.id} />
  </div>;
}
